environment:
  nodejs_version: "5.5.0"
  nodejs_arch: "x64"

install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  # install modules
  - npm install
  - npm install -g gulp
  - gulp

test_script:
  # run jest
  - npm test
  - gulp build

build: off
